version: "3"
services:
  iptv-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "iptv-proxy"
    restart: on-failure
    network_mode: "service:gluetun"
    environment:
      - M3U_URL=${M3U_URL}
      - PORT=8082
      # Hostname or IP to expose the IPTVs endpoints (for machine not for docker)
      - HOSTNAME=${HOSTNAME} 
      - GIN_MODE=release
      ## Xtream-code proxy configuration
      - XTREAM_USER=${AUTH_USERNAME}
      - XTREAM_PASSWORD=${AUTH_PASSWORD}
      - XTREAM_BASE_URL=https://tv.spazioidealemaerne.it
      ##### UNSAFE AUTH TODO ADD REAL AUTH
      #will be used for m3u and xtream auth poxy
      - USER=${AUTH_USERNAME}
      - PASSWORD=${AUTH_PASSWORD}
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp
      - 8082:8082/tcp
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PROTON_PRIVATE_KEY}
      - SERVER_COUNTRIES=Netherlands
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped

