version: "3"
services:
  iptv-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "iptv-proxy"
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      M3U_URL: http://cord-cutter.net:8080/get.php?username=30550113&password=30550113&type=m3u
      PORT: 8080
      # Hostname or IP to expose the IPTVs endpoints (for machine not for docker)
      HOSTNAME: localhost
      GIN_MODE: release
      ## Xtream-code proxy configuration
      #XTREAM_USER: xtream_user
      #XTREAM_PASSWORD: xtream_password
      #XTREAM_BASE_URL: "http://example.tv:8080"
      ##### UNSAFE AUTH TODO ADD REAL AUTH
      #will be used for m3u and xtream auth poxy
      USER: test
      PASSWORD: testpassword
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp
      - 8080:8080/tcp
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${PROTON_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${PROTON_ADDRESS}
      - SERVER_COUNTRIES=Switzerland
      - TZ=America/New_York
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24 # Your local subnet
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped

